create:
  fields:
    agent_ids:
      required: true
      example:
        - hassio.local
        - s3_compatible.example
      selector:
        text:
          multiple: true
    name:
      required: false
      example: "Backup 2026-09-27"
      selector:
        text:
    include_homeassistant:
      required: false
      default: true
      selector:
        boolean:
    include_database:
      required: false
      default: true
      selector:
        boolean:
    include_all_addons:
      required: false
      default: false
      selector:
        boolean:
    include_addons:
      required: false
      example:
        - core_mosquitto
      selector:
        text:
          multiple: true
    include_folders:
      required: false
      selector:
        select:
          multiple: true
          options:
            - share
            - addons/local
            - ssl
            - media
    password:
      required: false
      selector:
        text:
          type: password

delete:
  fields:
    backup_id:
      required: true
      example: "abc12345"
      selector:
        text:
    agent_ids:
      required: false
      example:
        - hassio.local
        - s3_compatible.example
      selector:
        text:
          multiple: true

list_backups: {}

get_backup:
  fields:
    backup_id:
      required: true
      example: "abc12345"
      selector:
        text:

list_agents: {}
